- id: sungai
  name: sungai
  entry: sungai
  language: python
  types: [python]
  require_serial: true
  description: 'Sungai is a directory tree rater.'
  pass_filenames: false
  stages: [commit, merge-commit, push, manual]
