fail_fast: true

# More at https://github.com/orgs/PyCQA/repositories
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: "6.1.0"
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/pylint
    rev: "v3.0.0"
    hooks:
      - id: pylint
        additional_dependencies: [
          "numpy==1.26.0",
          "gitignore_parser==0.1.9"
        ]
        exclude: tests/directory_tree
  - repo: https://github.com/pycqa/pydocstyle
    rev: "6.3.0"
    hooks:
      - id: pydocstyle
        exclude: tests/directory_tree
        additional_dependencies: [
          "toml~=0.10.2"
        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.5.1"
    hooks:
      - id: mypy
        name: mypy (sungai)
        files: ^sungai/
        additional_dependencies: [
          "numpy==1.26.0",
          "gitignore_parser==0.1.9"
        ]
        args:
          - "--warn-return-any"
          - "--warn-unused-configs"
          - "--warn-unused-ignores"
          - "--check-untyped-defs"
          - "--disallow-any-unimported"
          - "--disallow-untyped-defs"
          - "--ignore-missing-imports"
          - "--show-error-codes"
          - "--no-warn-return-any"
      - id: mypy
        name: mypy (tests)
        files: ^tests/
        additional_dependencies: [
          "numpy==1.26.0",
          "gitignore_parser==0.1.9"
        ]
        args:
          - "--warn-return-any"
          - "--warn-unused-configs"
          - "--warn-unused-ignores"
          - "--check-untyped-defs"
          - "--disallow-any-unimported"
          - "--disallow-untyped-defs"
          - "--ignore-missing-imports"
          - "--show-error-codes"
          - "--no-warn-return-any"
  - repo: https://github.com/regebro/pyroma
    rev: "4.2"
    hooks:
      - id: pyroma
  - repo: local
    hooks:
      - id: sungai
        name: sungai
        entry: sungai
        types: [python]
        language: system
        args: [./, "--min_score=0.9", "--ignore_config=.sungai_ignore"]
        pass_filenames: false
        always_run: true
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        exclude: tests/
