dist: jammy
language: python

on:
  push:
    branches: [ main, dev ]

matrix:
  include:
    - python: 3.9
    - python: 3.10
    - python: 3.11
    - python: 3.12

before_install:
  - pip install --upgrade pip

install:
  - pip install -r requirements-dev.txt --no-cache-dir
  - pip install sungai -e .
  - pre-commit install

script:
  - make lint
  - make test
