name: sungai CI

on:
  push:
    branches: [ main, dev ]

language: python
os: linux
dist: jammy

python:
  - 3.12-dev
  - 3.11
  - 3.10
  - 3.9

before_install:
  - pip install --upgrade pip

install:
  - chmod +x setup.sh
  - ./setup.sh

script:
  - make lint
  - make test

stage:
  - lint
  - test

jobs:
  exclude:
    - stage: lint
      python:
        - 3.12-dev
        - 3.11
        - 3.10
