dist: focal
language: python

on:
  push:
    branches: [ main, dev ]

matrix:
  include:
    - python: 3.8
    - python: 3.9
    - python: 3.10
    - python: 3.11

install:
  - pip install --upgrade pip
  - pip install -r requirements-dev.txt --no-cache-dir
  - pip install sungai==0.1.1
  - pre-commit install

script:
  - pre-commit run --all-files
  - coverage run -m unittest discover
  - tox -e py
