name: sungai CI

dist: jammy
language: python

on:
  push:
    branches: [ main, dev ]

jobs:
  include:
    - stage: lint
      python: 3.11
      before_install:
        - pip install --upgrade pip
      install:
        - chmod +x setup.sh
        - ./setup.sh
      script: make lint
    - stage: test
      matrix:
        include:
          - python: 3.9
          - python: 3.10
          - python: 3.11
          - python: 3.12-dev
      before_install:
        - pip install --upgrade pip
      install:
        - chmod +x setup.sh
        - ./setup.sh
      script: make test
