stages:
  - lint
  - test

on:
  push:
    branches: [ main, dev ]

language: python
os: linux
dist: jammy

before_install:
  - pip install --upgrade pip

install:
  - chmod +x setup.sh
  - ./setup.sh


jobs:
  include:
    - stage: lint
      python: 3.11
      script: make lint
    - stage: test
      python: "3.12-dev"
    - python: "3.11"
    - python: "3.10"
    - python: "3.9"
script: make test
