on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

os: linux
dist: jammy
language: python
python:
  # - "3.12-dev"
  - "3.11"
  - "3.10"
  - "3.9"

before_install:
  - pip install --upgrade pip

install:
  - chmod +x setup.sh
  - ./setup.sh

script:
  - make lint
  - make test
